name: Sync to A Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # B 저장소의 코드를 체크아웃합니다 (별도 토큰 불필요)
      - name: Checkout B Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # A 저장소의 SSH 키(deploy_key)를 이용해 A 저장소로 코드를 배포(덮어쓰기)합니다
      - name: Push to A Repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.A_REPO_DEPLOY_KEY }}
          external_repository: daniel-works0001/server-wakeup-bot
          publish_branch: main
          publish_dir: .
          force_orphan: true