name: Sync to A Repository

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때만 실행

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout B Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to A Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:daniel-works0001/server-wakeup-bot.git
          ssh_private_key:
            ${{ secrets.A_REPO_DEPLOY_KEY }}