name: Sync to A Repository

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때만 실행

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to A Repository
        uses: wearerequired/git-mirror-action@v1
        with:
          source_repo: "git@github.com:daniel-polio/server-wakeup-bot.git"
          destination_repo: "git@github.com:daniel-works0001/server-wakeup-bot.git"
          ssh_private_key: ${{ secrets.A_REPO_DEPLOY_KEY }}