name: Sync to A Repository

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때만 실행

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. B 저장소의 코드를 가져옵니다.
      - name: Checkout B Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. B 저장소의 Secret에 저장된 개인키를 Actions 실행기에 설치합니다.
      - name: Install SSH Key for A Repository
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.A_REPO_DEPLOY_KEY }}

      # 3. Git의 mirror 기능을 이용해 A 저장소로 푸시합니다.
      - name: Mirror to A Repository
        run: |
          git push git@github.com:daniel-works0001/server-wakeup-bot.git --mirror