name: Sync to A Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout B Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to A Repository using PAT
        uses: peaceiris/actions-gh-pages@v4
        with:
          # SSH Deploy Key 대신 PAT를 사용합니다.
          personal_token: ${{ secrets.A_REPO_PAT }}
          # 코드를 보낼 A 저장소의 주소
          external_repository: daniel-works0001/server-wakeup-bot
          # A 저장소의 main 브랜치로 보냄
          publish_branch: main
          publish_dir: .
          force_orphan: true
          # 커밋 작성자 정보를 명확히 지정
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com' 