name: Sync to A Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout B Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare publish directory (exclude internal sync workflow)
        run: |
          mkdir -p publish
          rsync -av --delete \
            --exclude '.git' \
            --exclude '.github/workflows/sync-to-a.yml' \
            ./ publish/

      - name: Commit and push to A/main using PAT
        env:
          A_REPO_PAT: ${{ secrets.A_REPO_PAT }}
        run: |
          cd publish
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "deploy(sync): mirror from B @ $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git branch -M main
          git remote add origin https://x-access-token:${A_REPO_PAT}@github.com/daniel-works0001/server-wakeup-bot.git
          # 브랜치 보호 규칙이 없다고 하셔서 --force 사용. 필요시 --force-with-lease로 교체 가능
          git push -u origin main --force