name: Sync to A Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout B Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare publish directory (exclude internal sync workflow)
        run: |
          mkdir -p publish
          rsync -av --delete \
            --exclude '.git' \
            --exclude '.github/workflows/sync-to-a.yml' \
            ./ publish/

      - name: Push to A using gh-pages action (PAT)
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.A_REPO_PAT }}
          external_repository: daniel-works0001/server-wakeup-bot
          publish_branch: main
          publish_dir: publish
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'